//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSheetManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentKit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentKit()
        {
            this.Equipments = new HashSet<Equipment>();
            this.EquipmentLocations = new HashSet<EquipmentLocation>();
        }
    
        public int Id { get; set; }
        public string Barcode { get; set; }
        public string Description { get; set; }
        public Nullable<int> EquipmentTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentLocation> EquipmentLocations { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
    }
}
