//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSheetManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentCalibration
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public string CertNumber { get; set; }
        public bool Passed { get; set; }
        public System.DateTime DtCalibrated { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
