//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSheetManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixServiceOverview
    {
        public Nullable<decimal> TotalDaysUsed { get; set; }
        public Nullable<decimal> Remaining { get; set; }
        public Nullable<decimal> PercentageUsed { get; set; }
        public Nullable<int> ContractDaysCompleted { get; set; }
        public Nullable<double> PercentageContractCompleted { get; set; }
        public int Id { get; set; }
    }
}
