//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSheetManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceSheetsEntities : DbContext
    {
        public ServiceSheetsEntities()
            : base("name=ServiceSheetsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MatrixServiceOverview> MatrixServiceOverviews { get; set; }
        public virtual DbSet<ServiceDay> ServiceDays { get; set; }
        public virtual DbSet<ServiceSheet> ServiceSheets { get; set; }
        public virtual DbSet<CanvasRawData> CanvasRawDatas { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentCalibration> EquipmentCalibrations { get; set; }
        public virtual DbSet<EquipmentKit> EquipmentKits { get; set; }
        public virtual DbSet<EquipmentLocation> EquipmentLocations { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
    }
}
